language: python
python:
    - '2.7'
addons:
    ssh_known_hosts: 46.37.163.252
before_install:
    - openssl aes-256-cbc -K $encrypted_5d52b09819ac_key -iv $encrypted_5d52b09819ac_iv -in deploy_key.enc -out deploy_key -d
install: pip install Sphinx
script:
    - sphinx-build -nW -b html -d build/doctrees source/ build/html
after_success:
    - chmod 600 deploy-key
    - mv deploy-key ~/.ssh/id_rsa
    - scp -r -p build/html/* root@46.37.163.252:/var/www/vhosts/docs.ukfast.co.uk/htdocs
    - ssh root@46.37.163.252 chown -R nginx.nginx /var/www/vhosts/docs.ukfast.co.uk/htdocs
